"""Spaltenlänge für 'ort' erhöht

Revision ID: 2431d1580889
Revises: 
Create Date: 2025-02-26 16:15:37.436184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2431d1580889'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('termin', schema=None) as batch_op:
        batch_op.alter_column('uhrzeit',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('termin', schema=None) as batch_op:
        batch_op.alter_column('uhrzeit',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)

    # ### end Alembic commands ###
