"""empty message

Revision ID: 3af6a96c1285
Revises: 6dd2e4ef07a5
Create Date: 2025-04-05 10:12:30.918927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3af6a96c1285'
down_revision = '6dd2e4ef07a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gallery_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gallery_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'gallery', ['gallery_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gallery_image', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('gallery_id')

    # ### end Alembic commands ###
