"""Initial migration

Revision ID: 6dd2e4ef07a5
Revises: 
Create Date: 2025-03-16 20:56:50.947695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dd2e4ef07a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('end_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('is_all_day', sa.Boolean(), nullable=True))
        batch_op.alter_column('start_time',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
        batch_op.alter_column('end_time',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.alter_column('end_time',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)
        batch_op.alter_column('start_time',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)
        batch_op.drop_column('is_all_day')
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')

    # ### end Alembic commands ###
